on: 
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing the action
    steps:
      - name: Checkout code
        id: checkout
        uses: Klaven/git-gha@main
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          action: Checkout
      - name: Make PR
        id: pr
        uses: Klaven/git-gha@main
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          tag: 'marek-testing'
          action: CommitPushPR
          base-pull-request: main
          target-pull-request: test
          pull-request-message: "this is a test"
          pull-request-title: ${{ github.event.pull_request.title }}